flowchart LR

    Student1["<b>student1 : Student</b><br/><br/>studentId = S101<br/>name = Geetanshi Jain<br/>email = geetanshi@example.com"]

    Poster1["<b>poster1 : Poster</b><br/><br/>posterId = P001<br/>title = AI in Water Management<br/>abstract = Smart water quality monitoring<br/>status = SUBMITTED"]

    Reviewer1["<b>reviewer1 : Reviewer</b><br/><br/>reviewerId = R001<br/>name = Dr. Sharma<br/>expertise = Artificial Intelligence"]

    Evaluation1["<b>evaluation1 : Evaluation</b><br/><br/>evaluationId = E001<br/>score = 88<br/>comments = Good research work<br/>status = COMPLETED"]

    Event1["<b>event1 : Event</b><br/><br/>eventId = EV001<br/>name = IIPS Research Symposium<br/>venue = IIPS DAVV<br/>year = 2026"]

    Student1 -->|"submits"| Poster1
    Poster1 -->|"submitted for"| Event1
    Reviewer1 -->|"evaluates"| Poster1
    Reviewer1 -->|"creates"| Evaluation1
    Evaluation1 -->|"for"| Poster1
