# Object Diagram

```mermaid
classDiagram

class Student {
    studentId
    name
    email
}

class Poster {
    posterId
    title
    abstract
    status
}

Student "1" --> "0..*" Poster : submits
```
