# Generated by Django 6.0.7 on 2026-10-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_results_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='criteria_list',
            field=models.JSONField(default=list),
        ),
    ]
