# Generated by Django 6.0.7 on 2026-10-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_criteria_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
